baseURL = "https://healthsaurus.netlify.com/"
languageCode = "en-us"
defaultContentLanguage = "en-us"
title = "Healthsaurus"
theme = "bootstrap"
  
[outputs]
home = ["HTML", "RSS"]

[Permalinks]
  post = "/:slug/"

[taxonomies]
  category = "categories"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    name = "getting started"
    url = "/getting-started/"
    weight = 2
    
  [[menu.main]]
    name = "cloud"
    url = "/cloud/"
    parent = "getting started"
