baseURL = "https://healthsaurus.netlify.com/"
languageCode = "en-us"
defaultContentLanguage = "en-us"
title = "Healthsaurus"
theme = "na"
  
[outputs]
home = ["HTML", "RSS"]

[Permalinks]
  post = "/:slug/"

[taxonomies]
  tag = "tags"
  category = "categories"
  archive = "archives"